includes:
- secret.yaml

#インストールされているバージョンによって末尾の数字調整
runtime: python39
service: default
# 下記は 設定用ディレクトリ.wsgi:application のように記述
entrypoint: gunicorn -b :$PORT private_diary.wsgi:application

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

- url: /_ah/mail/.+
  script: auto

inbound_services:
- mail