"""
Django settings for private_diary project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from .settings_common import *

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

DEBUG=True
ALLOWED_HOSTS=[os.environ.get('ALLOWED_HOSTS')]

if os.getenv('GAE_APPLICATION', None):
   # 本番環境
   DEBUG = True
   ALLOWED_HOSTS = ['redrockdiary.uc.r.appspot.com']
else:
   # 開発環境
   DEBUG = True
   ALLOWED_HOSTS = ['*']


#ロギング設定
LOGGING={
    'version': 1, #1固定
    'disable_existing_loggers': False,

    #ロガーの設定
    'loggers':{
        #Djangoが利用するロガー
        'django':{
            'handlers': ['console'],
            'level': 'INFO',
        },
        #diaryアプリケーションが利用するロガー
        'diary': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },

    #ハンドラの設定
    'handlers':{
        'console':{
            'level':'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'dev'
        },
    },

    #フォーマッタの設定
    'formatters': {
        'dev': {
            'format': '\t'.join([
                '%(asctime)s',
                '[%(levelname)s]',
                '%(pathname)s(Line:%(lineno)d)',
                '%(message)s'
            ])
        },
    }
}